server:
  port: 7777
 
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/soulmate?serverTimezone=Asia/Seoul&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true  		
        naming: 
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true       
       
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

clova:
  api:
    url: https://clovastudio.stream.ntruss.com/testapp
    endpoint:
      dash: /v3/chat-completions/HCX-DASH-002
      hcx007: /v3/chat-completions/HCX-007
      hcx005: /v3/chat-completions/HCX-005
      summary: /v1/api-tools/summarization/v2
    key: nv-6d80db4255ae41d987964a1c64a93820nTUJ

soulmate:
  answer-type:
    T: 이성을 기반으로 해결책을 제시
    F: 감정을 기반으로 해결책을 제시

logging:
  level:
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG
      